/*
 *  CVHomeViewCoordinates.h
 *  CapitalVueHD
 *
 *  Created by jishen on 10/19/10.
 *  Copyright 2010 SmilingMobile. All rights reserved.
 *
 */

// coordinates of today's news portlet
#define CVPORTLET_TODAY_NEWS_PORTRAIT_X       13
#define CVPORTLET_TODAY_NEWS_PORTRAIT_Y       20
#define CVPORTLET_TODAY_NEWS_PORTRAIT_WIDTH   739
#define CVPORTLET_TODAY_NEWS_PORTRAIT_HEIGHT  293

#define CVPORTLET_TODAY_NEWS_LANDSCAPE_X       16
#define CVPORTLET_TODAY_NEWS_LANDSCAPE_Y       20
#define CVPORTLET_TODAY_NEWS_LANDSCAPE_WIDTH  493
#define CVPORTLET_TODAY_NEWS_LANDSCAPE_HEIGHT 356

// coordinates of stock-in-the-news portlet
#define CVPORTLET_STOCK_IN_THE_NEW_PORTRAIT_X       13
#define CVPORTLET_STOCK_IN_THE_NEW_PORTRAIT_Y       328
#define CVPORTLET_STOCK_IN_THE_NEW_PORTRAIT_WIDTH   739
#define CVPORTLET_STOCK_IN_THE_NEW_PORTRAIT_HEIGHT  283

#define CVPORTLET_STOCK_IN_THE_NEW_LANDSCAPE_X      16
#define CVPORTLET_STOCK_IN_THE_NEW_LANDSCAPE_Y      392
#define CVPORTLET_STOCK_IN_THE_NEW_LANDSCAPE_WIDTH  493
#define CVPORTLET_STOCK_IN_THE_NEW_LANDSCAPE_HEIGHT 281

// coordinates of financial summary portlet
#define CVPORTLET_FINANCIAL_SUMMARY_PORTRAIT_X      13
#define CVPORTLET_FINANCIAL_SUMMARY_PORTRAIT_Y      631
#define CVPORTLET_FINANCIAL_SUMMARY_PORTRAIT_WIDTH  739
#define CVPORTLET_FINANCIAL_SUMMARY_PORTRAIT_HEIGHT 315

#define CVPORTLET_FINANCIAL_SUMMARY_LANDSCAPE_X      531
#define CVPORTLET_FINANCIAL_SUMMARY_LANDSCAPE_Y      20
#define CVPORTLET_FINANCIAL_SUMMARY_LANDSCAPE_WIDTH  462
#define CVPORTLET_FINANCIAL_SUMMARY_LANDSCAPE_HEIGHT 655