/*
 *  CVPortalSetMyStockCoordinates.h
 *  CapitalVueHD
 *
 *  Created by leon on 10-9-28.
 *  Copyright 2010 SmilingMobile. All rights reserved.
 *
 */

#define CVMYSTOCK_NAVIGATOR_DETAIL_PORTRAIT_X       20
#define CVMYSTOCK_NAVIGATOR_DETAIL_PORTRAIT_Y       20
#define CVMYSTOCK_NAVIGATOR_DETAIL_PORTRAIT_WIDTH   728
#define CVMYSTOCK_NAVIGATOR_DETAIL_PORTRAIT_HEIGHT  913

#define CVMYSTOCK_NAVIGATOR_DETAIL_LANDSCAPE_X      20
#define CVMYSTOCK_NAVIGATOR_DETAIL_LANDSCAPE_Y      20
#define CVMYSTOCK_NAVIGATOR_DETAIL_LANDSCAPE_WIDTH  980
#define CVMYSTOCK_NAVIGATOR_DETAIL_LANDSCAPE_HEIGHT 655

#define CVMYSTOCK_NAVIGATOR_LANDSCAPE_WIDTH  295
#define CVMYSTOCK_NAVIGATOR_LANDSCAPE_HEIGHT CVMYSTOCK_NAVIGATOR_DETAIL_LANDSCAPE_HEIGHT

#define CVMYSTOCK_DETAIL_ADDBUTTON_WIDTH     24
#define CVMYSTOCK_DETAIL_ADDBUTTON_HEIGHT    24

#define CVMYSTOCK_DETAIL_CLASSLABEL_WIDTH   120
#define CVMYSTOCK_DETAIL_CLASSLABEL_HEIGHT  30

// coordinates for stck chart view
#define CVMYSTOCK_DETAIL_CHART_PORTRAIT_X      23
#define CVMYSTOCK_DETAIL_CHART_PORTRAIT_Y      371
#define CVMYSTOCK_DETAIL_CHART_PORTRAIT_WIDTH  645
#define CVMYSTOCK_DETAIL_CHART_PORTRAIT_HEIGHT 322

#define CVMYSTOCK_DETAIL_CHART_LANDSCAPE_X     20
#define CVMYSTOCK_DETAIL_CHART_LANDSCAPE_Y     293
#define CVMYSTOCK_DETAIL_CHART_LANDSCAPE_WIDTH  645
#define CVMYSTOCK_DETAIL_CHART_LANDSCAPE_HEIGHT 322

// coordinates for detail info view controller
#define CVMYSTOCK_DETAIL_INFO_PORTRAIT_X        10
#define CVMYSTOCK_DETAIL_INFO_PORTRAIT_Y        60
#define CVMYSTOCK_DETAIL_INFO_PORTRAIT_WIDTH    668
#define CVMYSTOCK_DETAIL_INFO_PORTRAIT_HEIGHT   260

#define CVMYSTOCK_DETAIL_INFO_LANDSCAPE_X       5
#define CVMYSTOCK_DETAIL_INFO_LANDSCAPE_Y       40
#define CVMYSTOCK_DETAIL_INFO_LANDSCAPE_WIDTH   668
#define CVMYSTOCK_DETAIL_INFO_LANDSCAPE_HEIGHT  260

// coordinates for segment control
#define CVMYSTOCK_SEGMENT_CONTROL_PORTRAIT_X        330
#define CVMYSTOCK_SEGMENT_CONTROL_PORTRAIT_Y        (CVMYSTOCK_DETAIL_CHART_PORTRAIT_HEIGHT + 70)
#define CVMYSTOCK_SEGMENT_CONTROL_PORTRAIT_WIDTH    318
#define CVMYSTOCK_SEGMENT_CONTROL_PORTRAIT_HEIGHT   21

#define CVMYSTOCK_SEGMENT_CONTROL_LANDSCAPE_X       330
#define CVMYSTOCK_SEGMENT_CONTROL_LANDSCAPE_Y       (CVMYSTOCK_DETAIL_CHART_LANDSCAPE_HEIGHT)
#define CVMYSTOCK_SEGMENT_CONTROL_LANDSCAPE_WIDTH   318
#define CVMYSTOCK_SEGMENT_CONTROL_LANDSCAPE_HEIGHT  21

// coordinates for stock detail indicator
#define CVMYSTOCK_DETAIL_INDICATOR_PORTRAIT_X		343
#define CVMYSTOCK_DETAIL_INDICATOR_PORTRAIT_Y		420

#define CVMYSTOCK_DETAIL_INDICATOR_LANDSCAPE_X		340
#define CVMYSTOCK_DETAIL_INDICATOR_LANDSCAPE_Y		280