/*
 *  CVPortalSetMacroCoordinates.h
 *  CapitalVueHD
 *
 *  Created by jishen on 9/25/10.
 *  Copyright 2010 SmilingMobile. All rights reserved.
 *
 */

// navigator-detail frame size
#define CVMACRO_NAVIGATOR_DETAIL_PORTRAIT_X      20
#define CVMACRO_NAVIGATOR_DETAIL_PORTRAIT_Y      20
#define CVMACRO_NAVIGATOR_DETAIL_PORTRAIT_WIDTH  728
#define CVMACRO_NAVIGATOR_DETAIL_PORTRAIT_HEIGHT 913

#define CVMACRO_NAVIGATOR_DETAIL_LANDSCAPE_X       20
#define CVMACRO_NAVIGATOR_DETAIL_LANDSCAPE_Y       20
#define CVMACRO_NAVIGATOR_DETAIL_LANDSCAPE_WIDTH   980
#define CVMACRO_NAVIGATOR_DETAIL_LANDSCAPE_HEIGHT  655

#define CVMACRO_NAVIGATOR_LANDSCAPE_WIDTH  295
#define CVMACRO_NAVIGATOR_LANDSCAPE_HEIGHT CVMACRO_NAVIGATOR_DETAIL_LANDSCAPE_HEIGHT