/*
 *  CVMarketViewCoordinates.h
 *  CapitalVueHD
 *
 *  Created by jishen on 9/13/10.
 *  Copyright 2010 SmilingMobile. All rights reserved.
 *
 */

// frame size of composite index cover flow
#define CVPORTALET_MARKET_COMPOSITE_INDEX_PORTRAIT_X       20
#define CVPORTALET_MARKET_COMPOSITE_INDEX_PORTRAIT_Y       25
#define CVPORTALET_MARKET_COMPOSITE_INDEX_PORTRAIT_WIDTH   736
#define CVPORTALET_MARKET_COMPOSITE_INDEX_PORTRAIT_HEIGHT  339

#define CVPORTALET_MARKET_COMPOSITE_INDEX_LANDSCAPE_X      20
#define CVPORTALET_MARKET_COMPOSITE_INDEX_LANDSCAPE_Y      40
#define CVPORTALET_MARKET_COMPOSITE_INDEX_LANDSCAPE_WIDTH  973
#define CVPORTALET_MARKET_COMPOSITE_INDEX_LANDSCAPE_HEIGHT 339

#define CVPORTALET_MARKET_COMPOSITE_INDEX_COVER_WIDTH      250
#define CVPORTALET_MARKET_COMPOSITE_INDEX_COVER_HEIGHT     300

// frame size of most active
#define CVPORTALET_MARKET_MOST_ACTIVE_PORTRAIT_X           20
#define CVPORTALET_MARKET_MOST_ACTIVE_PORTRAIT_Y           377
#define CVPORTALET_MARKET_MOST_ACTIVE_PORTRAIT_WIDTH       727
#define CVPORTALET_MARKET_MOST_ACTIVE_PORTRAIT_HEIGHT      277

#define CVPORTALET_MARKET_MOST_ACTIVE_LANDSCAPE_X          20
#define CVPORTALET_MARKET_MOST_ACTIVE_LANDSCAPE_Y          406
#define CVPORTALET_MARKET_MOST_ACTIVE_LANDSCAPE_WIDTH      476
#define CVPORTALET_MARKET_MOST_ACTIVE_LANDSCAPE_HEIGHT     281

// frame size of stock
#define CVPORTALET_MARKET_STOCK_PORTRAIT_X                 20
#define CVPORTALET_MARKET_STOCK_PORTRAIT_Y                 668
#define CVPORTALET_MARKET_STOCK_PORTRAIT_WIDTH             727
#define CVPORTALET_MARKET_STOCK_PORTRAIT_HEIGHT            274

#define CVPORTALET_MARKET_STOCK_LANDSCAPE_X                519
#define CVPORTALET_MARKET_STOCK_LANDSCAPE_Y                406
#define CVPORTALET_MARKET_STOCK_LANDSCAPE_WIDTH            476
#define CVPORTALET_MARKET_STOCK_LANDSCAPE_HEIGHT           281

// content size of stock
#define TOP_MARKET_CAPITAL_LANDSCAPE_WIDTH 437
#define TOP_MARKET_CAPITAL_LANDSCAPE_HEIGHT 200

#define TOP_MARKET_CAPITAL_PORTRAIT_WIDTH 685
#define TOP_MARKET_CAPITAL_PORTRAIT_HEIGHT 187


//Notification key
#define kReloadMarketData	@"kReloadMarketData"